### ISSUE TITLE
View Attachment in article view

### ISSUE THREAD

**Issue by jikeseap** [jmcameron/attachments#40] opened 2024-03-26 08:26 UTC
Hello 

i migrate my joomla site from joomla 3 to joomla 4 before migration i unistall attachment plugin and after migration i install attachment 4 i had import the table with attachments in the db. everything it looks okey in the front end of the site i can see the attachments in each article and i can open it but when i open an article in article view it is not showing the attachment files. After looking the settings i find that it displays attachments in article view only in the articles of one specific category i don't know why is doing that i have seeing the settings to many time i cannot find something wrong.
can you help me please 

thank you in advance for your answer

**Comment by JLTRY** [comment] 2024-03-26 17:20
Hello do you have a screenshot of your parameters setting 
and one of your articles views . Is it a view of category categories, blog ? ...

**Comment by jikeseap** [comment] 2024-03-27 10:35
[error.pdf](https://github.com/jmcameron/attachments/files/14771912/error.pdf)
 i have attach a file with the settings and a link to the site if you open an article you see that is not showing the attachments that you see when you see the article in the main page 

thanks in advance

**Comment by jikeseap** [comment] 2024-03-28 06:34
> Hello do you have a screenshot of your parameters setting and one of your articles views . Is it a view of category categories, blog ? ... Do you have the url of the view not showing attachments ?

[error.pdf](https://github.com/jmcameron/attachments/files/14784896/error.pdf)
i have attach a file with the settings and a link to the site if you open an article you see that is not showing the attachments that you see when you see the article in the main page

thanks in advance

**Comment by JLTRY** [comment] 2024-03-28 20:30
Hello I did not reproduce this issue on my site see (http://www.jltryoen.fr/extensions-joomla/templates/136-installation-details-3)

**Comment by JLTRY** [comment] 2024-03-28 20:30
I will try to add log in file to be able to track ypur issue

**Comment by jikeseap** [comment] 2024-03-29 07:26
i can't open the link of your site is not accessible, i manage to find that the problem is  happening with the categories of my site when i create a new article category and i post a new article which i  choose to be in that new category everything is working. The article categories it have been created when the site was in joomla 3 version. i don't know if you can help me with that

**Comment by JLTRY** [comment] 2024-03-30 08:23
I have pushed a modification that you can try
 https://github.com/jmcameron/attachments/commit/e3f3b4baf00a04e2ff74f9fed0d9da86066ca1f5

**Comment by jikeseap** [comment] 2024-04-01 09:06
> I have pushed a modification that you can try [e3f3b4b](https://github.com/jmcameron/attachments/commit/e3f3b4baf00a04e2ff74f9fed0d9da86066ca1f5)

i try the changes and it work!!!!!!!!
Thank you for that 
i also see that in some article it displays the attachment twice as you can see in the screenshot that i have attach

thanks for everything
![error_double attachment](https://github.com/jmcameron/attachments/assets/10612082/3aeea504-b812-499f-90cf-739054919c15)

**Comment by JLTRY** [comment] 2024-04-06 14:20
I think for last issue it will be difficult to search for it . Do you have a link to the article ? What is special in it ? PErhaps short article ? is there a "Read more separator" in it ?

**Comment by jikeseap** [comment] 2024-04-16 05:52
Hello again 
the problem is the same from the beginning, before i change the code the attachments it was been displayed in the articles of some categories but not in the articles of all the categories. After i change the code you provide me the attachments is been displayed in the articles of all the categories but the article in the categories that they was displaying the attachments now it is displaying it twice

If i create a new category and move the article from an old category to that everything it looks okey

the link of the site development is https://dide.kas.sch.gr/upgrade/ 

thank you again for the help you provide me

**Comment by parapente** [comment] 2024-04-16 09:13
@jikeseap can you check if your <joomla prefix>__categories table in your database has correct extension (com_content), parent and path for those categories where attachments are not displayed?

**Comment by jikeseap** [comment] 2024-04-17 11:42
Hello again 
the problem is the same from the beginning, before i change the code the attachments it was been displayed in the articles of some categories but not in the articles of all the categories. After i change the code you provide me the attachments is been displayed in the articles of all the categories but the article in the categories that they was displaying the attachments now it is displaying it twice

If i create a new category and move the article from an old category to that everything it looks okey

the link of the site development is https://dide.kas.sch.gr/upgrade/ 

thank you again for the help you provide me

> @jikeseap can you check if your __categories table in your database has correct extension (com_content), parent and path for those categories where attachments are not displayed?

**Comment by jikeseap** [comment] 2024-04-17 11:46
everything in the database it looks okey as you can see in the image
![db_site](https://github.com/jmcameron/attachments/assets/10612082/5e199d18-9c20-44d5-bdd3-c829dde01d00)

**Comment by JLTRY** [comment] 2024-04-18 06:26
@parapente I have reverted the previous changes as you mentioned ( __the changes in https://github.com/jmcameron/attachments/commit/e3f3b4baf00a04e2ff74f9fed0d9da86066ca1f5 are causing the plugin to show the attachments two times in the article) It works for me so I will keep it in my branch

**Comment by JLTRY** [comment] 2024-04-18 19:54
I reverted my change in master branch as we have duplicated attachments
@jikeseap Can you please try [a8d4dfc](https://github.com/JLTRY/attachments/commit/a8d4dfccbd6ebaa1bc387dd393a5992dcce7b571)
to check if you have still duplicated entry

**Comment by parapente** [comment] 2024-04-21 11:03
@jikeseap @JLTRY check PR #45 for a possible fix on attachments not showing in blog articles and tell me if there are any other problems

**Comment by JLTRY** [comment] 2024-04-21 16:41
I merged  #45 into master branch

**Comment by jikeseap** [comment] 2024-04-22 06:10
> @jikeseap @JLTRY check PR #45 for a possible fix on attachments not showing in blog articles and tell me if there are any other problems

thank you very much both @parapente  @JLTRY

**Closed** 2024-04-22 06:17 UTC
